// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYWE0xxwab4aOzIf_yIeVx9LBa8HxZ4ic',
    appId: '1:1093002467794:web:c0407a577e00f04098100b',
    messagingSenderId: '1093002467794',
    projectId: 'test-a9764',
    authDomain: 'test-a9764.firebaseapp.com',
    storageBucket: 'test-a9764.appspot.com',
    measurementId: 'G-5XZ6GL9XE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1BL9gfTGfgfZImFfUmGvP-QeybpheMNM',
    appId: '1:1093002467794:android:272b682ba64f5a2798100b',
    messagingSenderId: '1093002467794',
    projectId: 'test-a9764',
    storageBucket: 'test-a9764.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMsg0X_wtIZeEdSSck02T07aQe0STLZuA',
    appId: '1:1093002467794:ios:4f4b379b019eadcf98100b',
    messagingSenderId: '1093002467794',
    projectId: 'test-a9764',
    storageBucket: 'test-a9764.appspot.com',
    iosBundleId: 'com.example.govQrEmp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMsg0X_wtIZeEdSSck02T07aQe0STLZuA',
    appId: '1:1093002467794:ios:4f4b379b019eadcf98100b',
    messagingSenderId: '1093002467794',
    projectId: 'test-a9764',
    storageBucket: 'test-a9764.appspot.com',
    iosBundleId: 'com.example.govQrEmp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYWE0xxwab4aOzIf_yIeVx9LBa8HxZ4ic',
    appId: '1:1093002467794:web:ef199ae60380ad9d98100b',
    messagingSenderId: '1093002467794',
    projectId: 'test-a9764',
    authDomain: 'test-a9764.firebaseapp.com',
    storageBucket: 'test-a9764.appspot.com',
    measurementId: 'G-KK5MNN927M',
  );

}